version: '3'
services:
#    face_recog_server:
#        container_name: "face_recognition"
#        image: ghcr.io/semantic-search/face_recog_gpu_api:latest
#        ports:
#            - 7000:7000
#        env_file:
#            - .env

    face_recog_indexer:
        build: .
        #image: ghcr.io/semantic-search/face_recognition_container:latest
        container_name : "kafka"
        env_file:
            - .env
