version: '3'
services:
    register:
        # image: jainal09/ingesting_common_cv:latest
        container_name : register
        build:
            context: .
            dockerfile: Dockerfile
        command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
        ports:
            - "8000:8000"
        expose:
            - "8000"
        env_file:
            - .env_file

    consumer:
        # image: jainal09/ingesting_common_cv:latest
        container_name : consumer
        build:
            context: .
            dockerfile: Dockerfile
        command: python3 main.py
        env_file:
            - .env_file
