version: '3'
services:
    face-recog-inference:
        build: .
        container_name: "face_recognition"
        image: ghcr.io/jainal09/face_recog:gpu
        command: uvicorn main:app --reload --host 0.0.0.0
        ports:
            - 7000:8000
        links:
            - mongodb
        depends_on:
            - mongodb

    consumer:
        # image: jainal09/ingesting_common_cv:latest
        container_name : consumer
        build:
            context: .
            dockerfile: Dockerfile
        command: python3 main.py
        env_file:
            - .env_file
